# Generated by Django 6.0.7 on 2026-07-31 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('node_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('prerequisite_node_id', models.CharField(blank=True, max_length=100, null=True)),
                ('next_node_id', models.CharField(blank=True, max_length=100, null=True)),
                ('core_concept', models.TextField()),
                ('difficulty_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64, unique=True)),
                ('stated_age', models.IntegerField(blank=True, null=True)),
                ('assessed_learning_age', models.CharField(default='unassessed', max_length=20)),
                ('domain_of_interest', models.CharField(default='general', max_length=100)),
                ('inspiration', models.CharField(blank=True, default='', max_length=150)),
                ('study_dislikes', models.TextField(blank=True, default='')),
                ('target_language', models.CharField(default='Tamil', max_length=50)),
                ('regional_dialect', models.CharField(default='Kongu Tamil', max_length=50)),
                ('current_persona_tone', models.CharField(default='warm and encouraging', max_length=50)),
                ('preferred_metaphor_domain', models.CharField(default='Panchatantra animals', max_length=50)),
                ('pacing_speed', models.CharField(default='slow and detailed', max_length=20)),
                ('frustration_score', models.IntegerField(default=0)),
                ('current_node_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MistakeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('user_answer', models.TextField()),
                ('ai_feedback', models.TextField(blank=True, default='')),
                ('fallback_node_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='core.learnerprofile')),
            ],
        ),
    ]
