# Generated by Django 6.0.7 on 2026-08-01 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('node_id', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('prerequisite_node_id', models.CharField(blank=True, max_length=140, null=True)),
                ('next_node_id', models.CharField(blank=True, max_length=140, null=True)),
                ('core_concept', models.TextField()),
                ('difficulty_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64, unique=True)),
                ('stated_age', models.IntegerField(blank=True, null=True)),
                ('prep_level', models.CharField(default='unassessed', max_length=50)),
                ('domain_of_interest', models.CharField(default='general', max_length=300)),
                ('mother_tongue', models.CharField(blank=True, default='', max_length=200)),
                ('birthplace', models.CharField(blank=True, default='', max_length=200)),
                ('residence', models.CharField(blank=True, default='', max_length=200)),
                ('languages_spoken', models.CharField(blank=True, default='', max_length=300)),
                ('psych_score', models.IntegerField(default=3)),
                ('psych_raw_answers', models.TextField(blank=True, default='')),
                ('assessed_learning_age', models.CharField(default='unassessed', max_length=20)),
                ('regional_dialect', models.CharField(default='', max_length=100)),
                ('current_persona_tone', models.CharField(default='warm and encouraging', max_length=50)),
                ('preferred_metaphor_domain', models.CharField(default='general', max_length=100)),
                ('pacing_speed', models.CharField(default='slow and detailed', max_length=20)),
                ('frustration_score', models.IntegerField(default=0)),
                ('current_node_id', models.CharField(default='', max_length=100)),
                ('last_icebreaker_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=140)),
                ('title', models.CharField(max_length=200)),
                ('mode', models.CharField(default='normal', max_length=20)),
                ('user_answer', models.TextField(blank=True, default='')),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.learnerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MistakeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=140)),
                ('user_answer', models.TextField()),
                ('ai_feedback', models.TextField(blank=True, default='')),
                ('fallback_node_id', models.CharField(blank=True, default='', max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='core.learnerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RelevanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevant_question', models.TextField()),
                ('relevant_answer', models.TextField(blank=True, default='')),
                ('irrelevant_question', models.TextField(blank=True, default='')),
                ('irrelevant_answer', models.TextField(blank=True, default='')),
                ('extracted_interest', models.CharField(blank=True, default='', max_length=200)),
                ('on_track', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevance_logs', to='core.learnerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Submodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('learning_material', models.TextField(blank=True, default='')),
                ('mermaid_diagram', models.TextField(blank=True, default='')),
                ('assignment_prompt', models.TextField(blank=True, default='')),
                ('assignment_answer', models.TextField(blank=True, default='')),
                ('assignment_done', models.BooleanField(default=False)),
                ('research_prompt', models.TextField(blank=True, default='')),
                ('research_done', models.BooleanField(default=False)),
                ('frustration_score', models.IntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='core.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField(blank=True, default='')),
                ('learning_objectives', models.TextField(blank=True, default='')),
                ('source_topic', models.CharField(max_length=200)),
                ('is_cross_domain', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='core.learnerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PrereqCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('questions_json', models.TextField()),
                ('answers_json', models.TextField(blank=True, default='')),
                ('pass_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_checks', to='core.learnerprofile')),
                ('escalated_to_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_from', to='core.track')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.track'),
        ),
        migrations.CreateModel(
            name='CurriculumIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('response_text', models.TextField()),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='core.learnerprofile')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='core.track')),
            ],
        ),
    ]
