# Generated by Django 6.0.7 on 2026-07-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='last_icebreaker_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
