# Generated by Django 6.0.7 on 2026-07-31 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_learnerprofile_last_icebreaker_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='psych_score',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='LessonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('mode', models.CharField(default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.learnerprofile')),
            ],
        ),
    ]
