# Generated by Django 6.0.7 on 2026-07-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_learnerprofile_psych_score_lessonlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='birthplace',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='mother_tongue',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='residence',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='lessonlog',
            name='passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonlog',
            name='user_answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
