# core/models.py
from django.db import models


class LearnerProfile(models.Model):
    user_id = models.CharField(max_length=64, unique=True)

    # --- From the onboarding quiz ---
    stated_age = models.IntegerField(null=True, blank=True)
    assessed_learning_age = models.CharField(max_length=20, default="unassessed")
    domain_of_interest = models.CharField(max_length=100, default="general")
    inspiration = models.CharField(max_length=150, blank=True, default="")
    study_dislikes = models.TextField(blank=True, default="")

    target_language = models.CharField(max_length=50, default="Tamil")
    regional_dialect = models.CharField(max_length=50, default="Kongu Tamil")

    # --- Adaptive persona state ---
    current_persona_tone = models.CharField(max_length=50, default="warm and encouraging")
    preferred_metaphor_domain = models.CharField(max_length=50, default="Panchatantra animals")
    pacing_speed = models.CharField(max_length=20, default="slow and detailed")
    frustration_score = models.IntegerField(default=0)

    current_node_id = models.CharField(max_length=100)

    def __str__(self):
        return self.user_id


class KnowledgeNode(models.Model):
    node_id = models.CharField(max_length=100, primary_key=True)
    title = models.CharField(max_length=200)
    prerequisite_node_id = models.CharField(max_length=100, null=True, blank=True)  # fallback routing
    next_node_id = models.CharField(max_length=100, null=True, blank=True)          # progression routing
    core_concept = models.TextField()  # ground-truth logic, never generated by the LLM
    difficulty_level = models.IntegerField(default=1)

    def __str__(self):
        return self.node_id


class MistakeLog(models.Model):
    learner = models.ForeignKey(LearnerProfile, on_delete=models.CASCADE, related_name="mistakes")
    node_id = models.CharField(max_length=100)
    user_answer = models.TextField()
    ai_feedback = models.TextField(blank=True, default="")
    fallback_node_id = models.CharField(max_length=100, blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.learner.user_id} @ {self.node_id} ({self.created_at:%H:%M:%S})"